/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


/*
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
*/


/**
 *
 * @author deciodecarvalho
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        
        initComponents();
       
       // lblConexao.setText("Conectado");
        
        //this.setResizable(false);
        this.setBounds(0, 0, 1200, 800);
        this.setIconImage(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConexao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        MenuCadastroClienteIncluir = new javax.swing.JMenuItem();
        MenuCadastroClienteConsultar = new javax.swing.JMenuItem();
        MenuCadastroClienteExcluir = new javax.swing.JMenuItem();
        MenuCadastroClientePesquisar = new javax.swing.JMenuItem();
        MenuVoo = new javax.swing.JMenu();
        MenuVooCadastro = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1Sair = new javax.swing.JMenu();
        jMenuSairSair = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuSobreTela = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Tutorial");

        lblConexao.setText(" ");

        jMenuArquivo.setText("Passagem");
        jMenuArquivo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/infraero/portal-financeiro.png"))); // NOI18N
        jMenuItem2.setText("Vender");
        jMenuArquivo.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/pesquisaLupaRed.png"))); // NOI18N
        jMenuItem3.setText("Consultar");
        jMenuArquivo.add(jMenuItem3);

        jMenuBar1.add(jMenuArquivo);

        jMenuCadastro.setText("Cliente");
        jMenuCadastro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        MenuCadastroClienteIncluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastroClienteIncluir.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MenuCadastroClienteIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente mulher laranja 40x40.jpg"))); // NOI18N
        MenuCadastroClienteIncluir.setText("Cliente Incluir");
        MenuCadastroClienteIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroClienteIncluirActionPerformed(evt);
            }
        });
        jMenuCadastro.add(MenuCadastroClienteIncluir);

        MenuCadastroClienteConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastroClienteConsultar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MenuCadastroClienteConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente verde 40x40.jpg"))); // NOI18N
        MenuCadastroClienteConsultar.setText("Cliente Alterar");
        MenuCadastroClienteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroClienteConsultarActionPerformed(evt);
            }
        });
        jMenuCadastro.add(MenuCadastroClienteConsultar);

        MenuCadastroClienteExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastroClienteExcluir.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MenuCadastroClienteExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir 40x40 vermelho.png"))); // NOI18N
        MenuCadastroClienteExcluir.setText("Cliente Excluir");
        jMenuCadastro.add(MenuCadastroClienteExcluir);

        MenuCadastroClientePesquisar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        MenuCadastroClientePesquisar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MenuCadastroClientePesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/pesquisar lupa amarela 40x40.jpg"))); // NOI18N
        MenuCadastroClientePesquisar.setText("Cliente Pequisar");
        jMenuCadastro.add(MenuCadastroClientePesquisar);

        jMenuBar1.add(jMenuCadastro);

        MenuVoo.setText("Voo");
        MenuVoo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        MenuVooCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        MenuVooCadastro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuVooCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/infraero/voos-on-line.png"))); // NOI18N
        MenuVooCadastro.setText("Cadastrar Voo");
        MenuVooCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVooCadastroActionPerformed(evt);
            }
        });
        MenuVoo.add(MenuVooCadastro);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/aeronave 40x40.jpg"))); // NOI18N
        jMenuItem1.setText("Cadastrar Aeronave");
        MenuVoo.add(jMenuItem1);

        jMenuBar1.add(MenuVoo);

        jMenu1Sair.setText("Sair");
        jMenu1Sair.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuSairSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuSairSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/SairBotao 40x40 vermelho.png"))); // NOI18N
        jMenuSairSair.setText("Sair");
        jMenuSairSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairSairActionPerformed(evt);
            }
        });
        jMenu1Sair.add(jMenuSairSair);

        jMenuBar1.add(jMenu1Sair);

        jMenuSobre.setText("Sobre");
        jMenuSobre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuSobreTela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        jMenuSobreTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/informcaoVerdinho i 40x40.png"))); // NOI18N
        jMenuSobreTela.setText("Sobre");
        jMenuSobreTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreTelaActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuSobreTela);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(lblConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblConexao)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSairSairActionPerformed

    private void MenuCadastroClienteIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroClienteIncluirActionPerformed
     src.Cadastro.montaTelaCliente();
    }//GEN-LAST:event_MenuCadastroClienteIncluirActionPerformed

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed
     
    }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void MenuCadastroClienteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroClienteConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCadastroClienteConsultarActionPerformed

    private void MenuVooCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVooCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuVooCadastroActionPerformed

    private void jMenuSobreTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreTelaActionPerformed
        // TODO add your handling code here:
       src.Cadastro.montaTelaAbout();
    }//GEN-LAST:event_jMenuSobreTelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        new TelaCadastro().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCadastroClienteConsultar;
    private javax.swing.JMenuItem MenuCadastroClienteExcluir;
    private javax.swing.JMenuItem MenuCadastroClienteIncluir;
    private javax.swing.JMenuItem MenuCadastroClientePesquisar;
    private javax.swing.JMenu MenuVoo;
    private javax.swing.JMenuItem MenuVooCadastro;
    private javax.swing.JMenu jMenu1Sair;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuSairSair;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenuItem jMenuSobreTela;
    public javax.swing.JLabel lblConexao;
    // End of variables declaration//GEN-END:variables
}
