/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Arrays;
import javax.swing.JOptionPane;
import src.ValidaCampos;

/**
 *
 * @author deciodecarvalho
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        cbxUF.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelClienteTitulo = new javax.swing.JPanel();
        JPanelClienteCadastro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        tftCPF = new javax.swing.JFormattedTextField();
        tftEmail = new javax.swing.JFormattedTextField();
        tftNascimento = new javax.swing.JFormattedTextField();
        tctNome = new javax.swing.JTextField();
        tftRG = new javax.swing.JFormattedTextField();
        tctEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        tctBairro = new javax.swing.JTextField();
        lblBairro1 = new javax.swing.JLabel();
        tctCidade = new javax.swing.JTextField();
        lblRG1 = new javax.swing.JLabel();
        tftCep = new javax.swing.JFormattedTextField();
        lblBairro2 = new javax.swing.JLabel();
        cbxUF = new javax.swing.JComboBox();
        JPanelClienteBotoes = new javax.swing.JPanel();
        btnSalvarCliente = new javax.swing.JButton();
        btnLimparCliente = new javax.swing.JButton();
        btnSairCliente = new javax.swing.JButton();
        lblTituloTelaClientes = new javax.swing.JLabel();
        lblTelaNomesTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JPanelClienteTituloLayout = new javax.swing.GroupLayout(JPanelClienteTitulo);
        JPanelClienteTitulo.setLayout(JPanelClienteTituloLayout);
        JPanelClienteTituloLayout.setHorizontalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        JPanelClienteTituloLayout.setVerticalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        lblNome.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(102, 102, 102));
        lblNome.setText("Nome:");

        lblEnd.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblEnd.setForeground(new java.awt.Color(102, 102, 102));
        lblEnd.setText("Endereço:");

        lblRG.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblRG.setForeground(new java.awt.Color(102, 102, 102));
        lblRG.setText("RG:");

        lblNascimento.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblNascimento.setForeground(new java.awt.Color(102, 102, 102));
        lblNascimento.setText("Nascimento:");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 102, 102));
        lblEmail.setText("Email:");

        lblCpf.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(102, 102, 102));
        lblCpf.setText("CPF:");

        try {
            tftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftCPF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        tftEmail.setForeground(new java.awt.Color(51, 51, 51));
        tftEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tftEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        try {
            tftNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftNascimento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        tctNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNome.setForeground(new java.awt.Color(51, 51, 51));
        tctNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        try {
            tftRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftRG.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        tctEndereco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctEndereco.setForeground(new java.awt.Color(51, 51, 51));
        tctEndereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblBairro.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(102, 102, 102));
        lblBairro.setText("Bairro");

        tctBairro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctBairro.setForeground(new java.awt.Color(51, 51, 51));
        tctBairro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblBairro1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblBairro1.setForeground(new java.awt.Color(102, 102, 102));
        lblBairro1.setText("Cidade:");

        tctCidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctCidade.setForeground(new java.awt.Color(51, 51, 51));
        tctCidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblRG1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblRG1.setForeground(new java.awt.Color(102, 102, 102));
        lblRG1.setText("CEP: ");

        try {
            tftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftCep.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        lblBairro2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblBairro2.setForeground(new java.awt.Color(102, 102, 102));
        lblBairro2.setText("UF: ");

        cbxUF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbxUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));

        btnSalvarCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarCliente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarGreen_1.png"))); // NOI18N
        btnSalvarCliente.setText("Salvar");
        btnSalvarCliente.setToolTipText("Salvar Alterações");
        btnSalvarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarCliente.setIconTextGap(2);
        btnSalvarCliente.setMargin(new java.awt.Insets(2, 2, 2, 14));
        btnSalvarCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        btnLimparCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparCliente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLimparCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/limpar.png"))); // NOI18N
        btnLimparCliente.setText("Limpar");
        btnLimparCliente.setMargin(new java.awt.Insets(2, 2, 2, 14));
        btnLimparCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparClienteActionPerformed(evt);
            }
        });

        btnSairCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnSairCliente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSairCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairCliente.setText("Voltar");
        btnSairCliente.setMargin(new java.awt.Insets(2, 2, 2, 14));
        btnSairCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelClienteBotoesLayout = new javax.swing.GroupLayout(JPanelClienteBotoes);
        JPanelClienteBotoes.setLayout(JPanelClienteBotoesLayout);
        JPanelClienteBotoesLayout.setHorizontalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteBotoesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnLimparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        JPanelClienteBotoesLayout.setVerticalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSairCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout JPanelClienteCadastroLayout = new javax.swing.GroupLayout(JPanelClienteCadastro);
        JPanelClienteCadastro.setLayout(JPanelClienteCadastroLayout);
        JPanelClienteCadastroLayout.setHorizontalGroup(
            JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                        .addComponent(lblRG)
                        .addGap(18, 18, 18)
                        .addComponent(tftRG, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCpf)
                        .addGap(18, 18, 18)
                        .addComponent(tftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelClienteCadastroLayout.createSequentialGroup()
                        .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tftEmail))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tctNome)
                                .addGap(31, 31, 31)
                                .addComponent(lblNascimento)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelClienteCadastroLayout.createSequentialGroup()
                        .addComponent(lblEnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tctEndereco))
                    .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                        .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(lblBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tctBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(lblBairro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tctCidade)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRG1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBairro2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxUF, 0, 117, Short.MAX_VALUE)
                            .addComponent(tftCep))))
                .addContainerGap())
            .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPanelClienteCadastroLayout.setVerticalGroup(
            JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblNascimento)
                    .addComponent(tftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnd)
                    .addComponent(tctEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(tctBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG1)
                    .addComponent(tftCep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxUF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBairro1)
                        .addComponent(tctCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBairro2)))
                .addGap(27, 27, 27)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(tftEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf)
                    .addComponent(tftRG, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG))
                .addGap(27, 27, 27)
                .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTituloTelaClientes.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblTituloTelaClientes.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloTelaClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTelaClientes.setText("Novo Cliente");

        lblTelaNomesTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Icones/Clientes2.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTelaNomesTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloTelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))
                    .addComponent(JPanelClienteCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloTelaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelaNomesTitulo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelClienteCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairClienteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairClienteActionPerformed

    private void btnLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparClienteActionPerformed
      
      tctBairro.setText(null);
      tftCep.setText(null);
      tctCidade.setText(null);
      cbxUF.setSelectedIndex(-1);
      tftCPF.setText(null);
      tftRG.setText(null);
      tftEmail.setText(null);
      tftNascimento.setText(null);
      tctNome.setText(null);
      tctEndereco.setText(null);
      
    }//GEN-LAST:event_btnLimparClienteActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
      
      String nome = tctNome.getText ();
      String nasc = tftNascimento.getText();
      String end = tctEndereco.getText();
      String email = tftEmail.getText();
      String rg = tftRG.getText();
      String cpf = tftCPF.getText();
      String cep = tftCep.getText();
      String bairro = tctBairro.getText();
      String cidade = tctCidade.getText();
      String uf = Arrays.toString(cbxUF.getSelectedObjects());
      
      
        //String email = this.tftEmail.getText();
        //String cpf = this.tftCPF.getText();
        
      String msg;
        msg = "";
        
       // email = this.tftEmail.getText().trim();
        System.out.println(rg);
        boolean validaNome = ValidaCampos.validaVazio(nome); 
        boolean validaEndereco = ValidaCampos.validaVazio(end);
        boolean validaData = ValidaCampos.validaData(nasc);
        boolean validaRG = ValidaCampos.validaRG(rg);
        boolean validaCPF = ValidaCampos.validaCPF(cpf);
        boolean validaEmail = ValidaCampos.validaEmail(email);
        boolean validaCep = ValidaCampos.validaCEP(cep);
        boolean validaCidade = ValidaCampos.validaVazio(cidade);
        boolean validaUF = ValidaCampos.validaVazioComboBox(uf);

        System.out.println(uf);
        
        
        if (validaNome) {
            } else {
              msg = msg + "Campo Nome Vazio" + "\n";
            }
        
        if (validaEndereco) {
            } else {
              msg = msg + "Campo Endereço Vazio" + "\n";
            }
        
        if (validaCep) {
            } else {
              msg = msg + "Campo CEP invalido: "+ cep + "\n";
              this.tftCep.setText(null);
            }
        
        if (validaCidade) {
            } else {
              msg = msg + "Campo Cidade Vazio" + "\n";
            }
        
                
        if (validaUF) {
            } else {
              msg = msg + "Campo UF Vazio" + "\n";
            }
        
        if (validaData) {
            } else {
              msg = msg + "Campo Nascimento invalido: "+ nasc + "\n";
              this.tftNascimento.setText(null);
            }
        
        if (validaEmail) {
            } else {
              msg = msg +"Campo E-mail invalido: "+ email + "\n";
              this.tftEmail.setText(null);
            }
        if (validaRG) {
            } else {
              msg = msg + "Campo RG invalido: "+ rg + "\n";
              this.tftRG.setText(null);
            }  
        
        if (validaCPF) {
            } else {
              msg = msg + "Campo CPF invalido: "+ cpf + "\n";
              this.tftCPF.setText(null);
            }
        
          
          
        //msg = msg +"oi oi oi \n";
          
         if ("".equals(msg)){
         msg = "Dados Enviados ao banco de dados do sistema!";
             //incluirDados(nome, nasc, end, email, rg, cpf);
        JOptionPane.showMessageDialog(this, msg,"Dados Enviados", JOptionPane.INFORMATION_MESSAGE);
        btnLimparCliente.doClick();
         }
        else{
        JOptionPane.showMessageDialog(this, msg,"Campo Inválido ou vazio", JOptionPane.ERROR_MESSAGE );
        }      
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelClienteBotoes;
    private javax.swing.JPanel JPanelClienteCadastro;
    private javax.swing.JPanel JPanelClienteTitulo;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnSairCliente;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JComboBox cbxUF;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBairro1;
    private javax.swing.JLabel lblBairro2;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRG1;
    private javax.swing.JLabel lblTelaNomesTitulo;
    private javax.swing.JLabel lblTituloTelaClientes;
    private javax.swing.JTextField tctBairro;
    private javax.swing.JTextField tctCidade;
    private javax.swing.JTextField tctEndereco;
    private static javax.swing.JTextField tctNome;
    private javax.swing.JFormattedTextField tftCPF;
    private javax.swing.JFormattedTextField tftCep;
    private javax.swing.JFormattedTextField tftEmail;
    private javax.swing.JFormattedTextField tftNascimento;
    private javax.swing.JFormattedTextField tftRG;
    // End of variables declaration//GEN-END:variables

    
}
