/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import src.ValidaCampos;
import src.DBDerby;
/**
 *
 * @author deciodecarvalho
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelClienteTitulo = new javax.swing.JPanel();
        JPanelClienteCadastro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        tftCPF = new javax.swing.JFormattedTextField();
        tftEmail = new javax.swing.JFormattedTextField();
        tftNascimento = new javax.swing.JFormattedTextField();
        tctNome = new javax.swing.JTextField();
        tftRG = new javax.swing.JFormattedTextField();
        tctEndereco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTelaNomesTitulo = new javax.swing.JLabel();
        JPanelClienteBotoes = new javax.swing.JPanel();
        btnSalvarCliente = new javax.swing.JButton();
        btnLimparCliente = new javax.swing.JButton();
        btnSairCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JPanelClienteTituloLayout = new javax.swing.GroupLayout(JPanelClienteTitulo);
        JPanelClienteTitulo.setLayout(JPanelClienteTituloLayout);
        JPanelClienteTituloLayout.setHorizontalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );
        JPanelClienteTituloLayout.setVerticalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblEnd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEnd.setText("Endereço:");

        lblRG.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRG.setText("RG:");

        lblNascimento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNascimento.setText("Nascimento:");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEmail.setText("Email:");

        lblCpf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCpf.setText("CPF:");

        try {
            tftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tftEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tftNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        tftNascimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tctNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        try {
            tftRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftRG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tctEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout JPanelClienteCadastroLayout = new javax.swing.GroupLayout(JPanelClienteCadastro);
        JPanelClienteCadastro.setLayout(JPanelClienteCadastroLayout);
        JPanelClienteCadastroLayout.setHorizontalGroup(
            JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRG, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(tctEndereco)
                                .addGap(46, 46, 46)
                                .addComponent(lblEmail))
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(tftRG, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCpf))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteCadastroLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tctNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNascimento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tftCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(tftEmail)
                    .addComponent(tftNascimento))
                .addGap(53, 53, 53))
        );
        JPanelClienteCadastroLayout.setVerticalGroup(
            JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblNascimento)
                    .addComponent(tftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnd)
                    .addComponent(lblEmail)
                    .addComponent(tftEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRG)
                    .addComponent(lblCpf)
                    .addComponent(tftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Novo Cliente");

        lblTelaNomesTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/pessoaFisica.jpeg"))); // NOI18N

        btnSalvarCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarCliente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarGreen_1.png"))); // NOI18N
        btnSalvarCliente.setText("Salvar");
        btnSalvarCliente.setToolTipText("Salvar Alterações");
        btnSalvarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarCliente.setIconTextGap(2);
        btnSalvarCliente.setMargin(new java.awt.Insets(2, 2, 2, 14));
        btnSalvarCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        btnLimparCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparCliente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLimparCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/limpar.png"))); // NOI18N
        btnLimparCliente.setText("Limpar");
        btnLimparCliente.setMargin(new java.awt.Insets(2, 2, 2, 14));
        btnLimparCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparClienteActionPerformed(evt);
            }
        });

        btnSairCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnSairCliente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSairCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairCliente.setText("Voltar");
        btnSairCliente.setMargin(new java.awt.Insets(2, 2, 2, 14));
        btnSairCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelClienteBotoesLayout = new javax.swing.GroupLayout(JPanelClienteBotoes);
        JPanelClienteBotoes.setLayout(JPanelClienteBotoesLayout);
        JPanelClienteBotoesLayout.setHorizontalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteBotoesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnLimparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        JPanelClienteBotoesLayout.setVerticalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSairCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTelaNomesTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260))
                    .addComponent(JPanelClienteCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelaNomesTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(JPanelClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairClienteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairClienteActionPerformed

    private void btnLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparClienteActionPerformed
      
      tftCPF.setText(null);
      tftRG.setText(null);
      tftEmail.setText(null);
      tftNascimento.setText(null);
      tctNome.setText(null);
      tctEndereco.setText(null);
      
    }//GEN-LAST:event_btnLimparClienteActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
      
      String nome = tctNome.getText ();
      String nasc = tftNascimento.getText();
      String end = tctEndereco.getText();
      String email = tftEmail.getText();
      String rg = tftRG.getText();
      String cpf = tftCPF.getText();
      
        //String email = this.tftEmail.getText();
        //String cpf = this.tftCPF.getText();
        
      String msg;
        msg = "";
        
       // email = this.tftEmail.getText().trim();
       
       // boolean validaCPF = ValidaCampos.validaCPF(cpf);
        boolean validaEmail = ValidaCampos.validaEmail(email);
        System.out.println(cpf);
          if (validaEmail) {
            } else {
              msg = msg +"Campo E-mail invalido: "+ email + "\n";
              this.tftEmail.setText(null);
            }
          
         /* if (validaCPF) {
            } else {
              msg = msg + "Campo CPF invalido: "+ cpf + "\n";
              this.tftCPF.setText(null);
            }
        */
           msg = msg +"oi oi oi \n";
          
         if (msg==null){
            //incluirDados(nome, nasc, end, email, rg, cpf);
        }
        else{
        JOptionPane.showMessageDialog(null, msg,"Campo Inválido", JOptionPane.ERROR_MESSAGE);
        }      
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelClienteBotoes;
    private javax.swing.JPanel JPanelClienteCadastro;
    private javax.swing.JPanel JPanelClienteTitulo;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnSairCliente;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblTelaNomesTitulo;
    private javax.swing.JTextField tctEndereco;
    private javax.swing.JTextField tctNome;
    private javax.swing.JFormattedTextField tftCPF;
    private javax.swing.JFormattedTextField tftEmail;
    private javax.swing.JFormattedTextField tftNascimento;
    private javax.swing.JFormattedTextField tftRG;
    // End of variables declaration//GEN-END:variables
}
